### ISSUE TITLE
Random crashes after a while

### ISSUE THREAD

**Issue by Delta4Phoenix** [Knsgf/SE-diff-throttling-WM-#1]
[log.zip](https://github.com/Knsgf/SE-diff-throttling-WM-/files/4774561/log.zip)

As said in the title, after a while of playing, the game just crashes. I sadly do not know why.

**Comment by Knsgf** [comment]
The link to the world is still necessary to reproduce the issue.

**Comment by Delta4Phoenix** [comment]
Good luck, the map is broken beyond repair after deleting the mod cache.
https://steamcommunity.com/sharedfiles/filedetails/?id=2129128057

**Comment by Knsgf** [comment]
Resolved.
